// ReSharper disable CommentTypo
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable IdentifierTypo
// ReSharper disable UnusedType.Global
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable EventNeverSubscribedTo.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable CheckNamespace
// ReSharper disable StringLiteralTypo
// ReSharper disable MemberHidesStaticFromOuterClass
// This code was automatically generated by GDExtension C# Bindgen

using Godot;

namespace GDExtensionBindgen;

public class LuaUserdata : LuaTable
{
    public LuaUserdata() : base(NativeName)
    {
    }

    protected LuaUserdata(StringName @class) : base(@class)
    {
    }

    protected LuaUserdata(Variant variant) : base(variant)
    {
    }

    protected LuaUserdata(RefCounted @object) : base(@object)
    {
    }

    public static implicit operator RefCounted(LuaUserdata self) => self.Object;
    public static implicit operator Variant(LuaUserdata self) => self.Object;
    public static explicit operator LuaUserdata(Variant variant) => new(variant.AsGodotObject());

    public new class PropertyName : LuaTable.PropertyName
    {
    }

    public new class MethodName : LuaTable.MethodName
    {
    }

    public new class SignalName : LuaTable.SignalName
    {
    }

    private static readonly StringName NativeName = "LuaUserdata";
}