// ReSharper disable CommentTypo
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable IdentifierTypo
// ReSharper disable UnusedType.Global
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable EventNeverSubscribedTo.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable StringLiteralTypo
// ReSharper disable MemberHidesStaticFromOuterClass
// This code was automatically generated by GDExtension C# Bindgen

using Godot;

namespace GUITest.scripts.Proxy;

public class LuaLightUserdata : LuaObject
{
    public LuaLightUserdata() : base(NativeName)
    {
    }

    protected LuaLightUserdata(StringName @class) : base(@class)
    {
    }

    protected LuaLightUserdata(Variant variant) : base(variant)
    {
    }

    protected LuaLightUserdata(RefCounted @object) : base(@object)
    {
    }

    public static implicit operator RefCounted(LuaLightUserdata self) => self.Object;
    public static implicit operator Variant(LuaLightUserdata self) => self.Object;
    public static explicit operator LuaLightUserdata(Variant variant) => new(variant.AsGodotObject());

    public new class PropertyName : LuaObject.PropertyName
    {
    }

    public new class MethodName : LuaObject.MethodName
    {
    }

    public new class SignalName : LuaObject.SignalName
    {
    }

    private static readonly StringName NativeName = "LuaLightUserdata";
}